In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
print("Pandas Version:", pd.__version__)
print("NumPy Version:", np.__version__)

Pandas Version: 2.3.2
NumPy Version: 2.2.5

In [4]:
commodity = pd.read_csv("commodity_prices.csv")
crop = pd.read_csv("crop_yields.csv")
fsi = pd.read_csv("food_security_indicators.csv")
panel = pd.read_csv("food_security_panel.csv")

In [5]:
commodity.head()

,date,soybean_oil_usd_mt,maize_usd_mt,wheat_usd_mt,dap_fertiliser_usd_mt,mop_potash_usd_mt,wheat_usd_mt_mom_pct,wheat_usd_mt_yoy_pct,maize_usd_mt_mom_pct,maize_usd_mt_yoy_pct,soybean_oil_usd_mt_mom_pct,soybean_oil_usd_mt_yoy_pct,dap_fertiliser_usd_mt_mom_pct,dap_fertiliser_usd_mt_yoy_pct,mop_potash_usd_mt_mom_pct,mop_potash_usd_mt_yoy_pct,dap_to_wheat_ratio,fertiliser_composite_idx
0,1960-01-31,204.0,45.0,59.89,NaN,28.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.5
1,1960-02-29,201.0,44.0,60.99,NaN,28.5,1.837,NaN,-2.222,NaN,-1.471,NaN,NaN,NaN,0.0,NaN,NaN,28.5
2,1960-03-31,201.0,45.0,61.73,NaN,28.5,1.213,NaN,2.273,NaN,0.000,NaN,NaN,NaN,0.0,NaN,NaN,28.5
3,1960-04-30,207.0,45.0,60.99,NaN,28.5,-1.199,NaN,0.000,NaN,2.985,NaN,NaN,NaN,0.0,NaN,NaN,28.5
4,1960-05-31,209.0,48.0,57.69,NaN,28.5,-5.411,NaN,6.667,NaN,0.966,NaN,NaN,NaN,0.0,NaN,NaN,28.5

In [6]:
crop.head()

,year,maize_area_mha,maize_production_mt,rice_paddy_area_mha,rice_paddy_production_mt,wheat_area_mha,wheat_production_mt,wheat_production_mt_yoy_pct,rice_paddy_production_mt_yoy_pct,maize_production_mt_yoy_pct,total_staple_production_mt
0,1961,105559.547,205027.236,115365.128,215646.627,204209.450,222357.231,NaN,NaN,NaN,643031.094
1,1962,103496.472,204876.636,119452.412,226456.291,207554.518,250319.146,12.575,5.013,-0.073,681652.073
2,1963,108427.427,220228.115,120151.874,247119.204,206130.240,233339.473,-6.783,9.124,7.493,700686.792
3,1964,107925.069,215172.391,125056.092,262928.949,216539.177,268791.657,15.193,6.398,-2.296,746892.997
4,1965,106676.499,226544.121,124828.866,254059.657,216979.762,263645.963,-1.914,-3.373,5.285,744249.741

In [7]:
fsi.head()

,year,undernourishment_pct,food_production_index,cereal_yield_kg_ha,arable_land_pct,undernourishment_pct_yoy_chg,food_production_index_yoy_chg,cereal_yield_kg_ha_yoy_chg
0,1961,NaN,12.899822,NaN,NaN,NaN,NaN,NaN
1,1962,NaN,13.174495,NaN,NaN,NaN,0.275,NaN
2,1963,NaN,13.789956,NaN,9.642818,NaN,0.615,NaN
3,1964,NaN,13.510396,1576.946325,9.663356,NaN,-0.280,NaN
4,1965,NaN,13.635739,1625.014969,9.694099,NaN,0.125,48.069

In [8]:
panel.head()

,date,soybean_oil_usd_mt,maize_usd_mt,wheat_usd_mt,dap_fertiliser_usd_mt,mop_potash_usd_mt,wheat_usd_mt_mom_pct,wheat_usd_mt_yoy_pct,maize_usd_mt_mom_pct,maize_usd_mt_yoy_pct,...,ffpi_cereals_yoy_pct,ffpi_above_baseline,ffpi_crisis_flag,dap_to_wheat_elevated,ffpi_volatility_12m,cereals_affordability_idx,supply_stress_flag,food_shock_score,month,year
0,1990-01-31,417.0,105.60,167.92,138.500,98.500,2.011,-3.383,-3.270,-10.660,...,NaN,0,0,0,NaN,145.43,0,0,1,1990
1,1990-02-28,428.0,106.07,160.94,139.750,98.500,-4.157,-6.408,0.445,-9.666,...,NaN,0,0,0,NaN,148.61,0,0,2,1990
2,1990-03-31,442.0,109.70,156.53,146.000,97.375,-2.740,-12.165,3.422,-7.332,...,NaN,0,0,0,NaN,148.52,0,0,3,1990
3,1990-04-30,440.0,118.82,159.47,155.200,93.200,1.878,-8.629,8.314,2.661,...,NaN,0,0,0,NaN,141.60,0,0,4,1990
4,1990-05-31,449.0,121.04,149.18,149.125,93.500,-6.453,-15.416,1.868,2.890,...,NaN,0,0,0,NaN,145.12,0,0,5,1990

In [9]:
commodity.shape

(780, 18)

In [10]:
commodity.columns

Index(['date', 'soybean_oil_usd_mt', 'maize_usd_mt', 'wheat_usd_mt',
       'dap_fertiliser_usd_mt', 'mop_potash_usd_mt', 'wheat_usd_mt_mom_pct',
       'wheat_usd_mt_yoy_pct', 'maize_usd_mt_mom_pct', 'maize_usd_mt_yoy_pct',
       'soybean_oil_usd_mt_mom_pct', 'soybean_oil_usd_mt_yoy_pct',
       'dap_fertiliser_usd_mt_mom_pct', 'dap_fertiliser_usd_mt_yoy_pct',
       'mop_potash_usd_mt_mom_pct', 'mop_potash_usd_mt_yoy_pct',
       'dap_to_wheat_ratio', 'fertiliser_composite_idx'],
      dtype='object')

In [11]:
commodity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           780 non-null    object
 1   soybean_oil_usd_mt             780 non-null    float64
 2   maize_usd_mt                   780 non-null    float64
 3   wheat_usd_mt                   780 non-null    float64
 4   dap_fertiliser_usd_mt          696 non-null    float64
 5   mop_potash_usd_mt              780 non-null    float64
 6   wheat_usd_mt_mom_pct           779 non-null    float64
 7   wheat_usd_mt_yoy_pct           768 non-null    float64
 8   maize_usd_mt_mom_pct           779 non-null    float64
 9   maize_usd_mt_yoy_pct           768 non-null    float64
 10  soybean_oil_usd_mt_mom_pct     779 non-null    float64
 11  soybean_oil_usd_mt_yoy_pct     768 non-null    float64
 12  dap_fertiliser_usd_mt_mom_pct  695 non-null    float64
 13  dap_fertiliser_usd_mt_yoy_pct  684 non-null    float64
 14  mop_potash_usd_mt_mom_pct      779 non-null    float64
 15  mop_potash_usd_mt_yoy_pct      768 non-null    float64
 16  dap_to_wheat_ratio             696 non-null    float64
 17  fertiliser_composite_idx       780 non-null    float64
dtypes: float64(17), object(1)
memory usage: 106.7+ KB

In [12]:
crop.shape

(64, 11)

In [13]:
crop.columns

Index(['year', 'maize_area_mha', 'maize_production_mt', 'rice_paddy_area_mha',
       'rice_paddy_production_mt', 'wheat_area_mha', 'wheat_production_mt',
       'wheat_production_mt_yoy_pct', 'rice_paddy_production_mt_yoy_pct',
       'maize_production_mt_yoy_pct', 'total_staple_production_mt'],
      dtype='object')

In [14]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   year                              64 non-null     int64
 1   maize_area_mha                    64 non-null     float64
 2   maize_production_mt               64 non-null     float64
 3   rice_paddy_area_mha               64 non-null     float64
 4   rice_paddy_production_mt          64 non-null     float64
 5   wheat_area_mha                    64 non-null     float64
 6   wheat_production_mt               64 non-null     float64
 7   wheat_production_mt_yoy_pct       63 non-null     float64
 8   rice_paddy_production_mt_yoy_pct  63 non-null     float64
 9   maize_production_mt_yoy_pct       63 non-null     float64
 10  total_staple_production_mt        64 non-null     float64
dtypes: float64(10), int64(1)
memory usage: 5.6 KB

In [15]:
fsi.shape

(63, 8)

In [16]:
fsi.columns

Index(['year', 'undernourishment_pct', 'food_production_index',
       'cereal_yield_kg_ha', 'arable_land_pct', 'undernourishment_pct_yoy_chg',
       'food_production_index_yoy_chg', 'cereal_yield_kg_ha_yoy_chg'],
      dtype='object')

In [17]:
fsi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   year                           63 non-null     int64
 1   undernourishment_pct           23 non-null     float64
 2   food_production_index          60 non-null     float64
 3   cereal_yield_kg_ha             60 non-null     float64
 4   arable_land_pct                60 non-null     float64
 5   undernourishment_pct_yoy_chg   22 non-null     float64
 6   food_production_index_yoy_chg  59 non-null     float64
 7   cereal_yield_kg_ha_yoy_chg     59 non-null     float64
dtypes: float64(7), int64(1)
memory usage: 4.0 KB

In [18]:
panel.shape

(420, 38)

In [19]:
panel.columns

Index(['date', 'soybean_oil_usd_mt', 'maize_usd_mt', 'wheat_usd_mt',
       'dap_fertiliser_usd_mt', 'mop_potash_usd_mt', 'wheat_usd_mt_mom_pct',
       'wheat_usd_mt_yoy_pct', 'maize_usd_mt_mom_pct', 'maize_usd_mt_yoy_pct',
       'soybean_oil_usd_mt_mom_pct', 'soybean_oil_usd_mt_yoy_pct',
       'dap_fertiliser_usd_mt_mom_pct', 'dap_fertiliser_usd_mt_yoy_pct',
       'mop_potash_usd_mt_mom_pct', 'mop_potash_usd_mt_yoy_pct',
       'dap_to_wheat_ratio', 'fertiliser_composite_idx',
       'undernourishment_pct', 'food_production_index', 'cereal_yield_kg_ha',
       'arable_land_pct', 'undernourishment_pct_yoy_chg',
       'food_production_index_yoy_chg', 'cereal_yield_kg_ha_yoy_chg',
       'ffpi_overall', 'ffpi_cereals', 'ffpi_overall_mom_pct',
       'ffpi_cereals_yoy_pct', 'ffpi_above_baseline', 'ffpi_crisis_flag',
       'dap_to_wheat_elevated', 'ffpi_volatility_12m',
       'cereals_affordability_idx', 'supply_stress_flag', 'food_shock_score',
       'month', 'year'],
      dtype='object')

In [20]:
panel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 38 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           420 non-null    object
 1   soybean_oil_usd_mt             420 non-null    float64
 2   maize_usd_mt                   420 non-null    float64
 3   wheat_usd_mt                   420 non-null    float64
 4   dap_fertiliser_usd_mt          420 non-null    float64
 5   mop_potash_usd_mt              420 non-null    float64
 6   wheat_usd_mt_mom_pct           420 non-null    float64
 7   wheat_usd_mt_yoy_pct           420 non-null    float64
 8   maize_usd_mt_mom_pct           420 non-null    float64
 9   maize_usd_mt_yoy_pct           420 non-null    float64
 10  soybean_oil_usd_mt_mom_pct     420 non-null    float64
 11  soybean_oil_usd_mt_yoy_pct     420 non-null    float64
 12  dap_fertiliser_usd_mt_mom_pct  420 non-null    float64
 13  dap_fertiliser_usd_mt_yoy_pct  420 non-null    float64
 14  mop_potash_usd_mt_mom_pct      420 non-null    float64
 15  mop_potash_usd_mt_yoy_pct      420 non-null    float64
 16  dap_to_wheat_ratio             420 non-null    float64
 17  fertiliser_composite_idx       420 non-null    float64
 18  undernourishment_pct           276 non-null    float64
 19  food_production_index          383 non-null    float64
 20  cereal_yield_kg_ha             419 non-null    float64
 21  arable_land_pct                407 non-null    float64
 22  undernourishment_pct_yoy_chg   264 non-null    float64
 23  food_production_index_yoy_chg  383 non-null    float64
 24  cereal_yield_kg_ha_yoy_chg     419 non-null    float64
 25  ffpi_overall                   420 non-null    float64
 26  ffpi_cereals                   420 non-null    float64
 27  ffpi_overall_mom_pct           419 non-null    float64
 28  ffpi_cereals_yoy_pct           408 non-null    float64
 29  ffpi_above_baseline            420 non-null    int64
 30  ffpi_crisis_flag               420 non-null    int64
 31  dap_to_wheat_elevated          420 non-null    int64
 32  ffpi_volatility_12m            408 non-null    float64
 33  cereals_affordability_idx      420 non-null    float64
 34  supply_stress_flag             420 non-null    int64
 35  food_shock_score               420 non-null    int64
 36  month                          420 non-null    int64
 37  year                           420 non-null    int64
dtypes: float64(30), int64(7), object(1)
memory usage: 123.1+ KB

In [21]:
print("Commodity:", commodity.shape)
print("Crop:", crop.shape)
print("Food Security Indicators:", fsi.shape)
print("Food Security Panel:", panel.shape)

Commodity: (780, 18)
Crop: (64, 11)
Food Security Indicators: (63, 8)
Food Security Panel: (420, 38)

In [22]:
commodity.dtypes

date                              object
soybean_oil_usd_mt               float64
maize_usd_mt                     float64
wheat_usd_mt                     float64
dap_fertiliser_usd_mt            float64
mop_potash_usd_mt                float64
wheat_usd_mt_mom_pct             float64
wheat_usd_mt_yoy_pct             float64
maize_usd_mt_mom_pct             float64
maize_usd_mt_yoy_pct             float64
soybean_oil_usd_mt_mom_pct       float64
soybean_oil_usd_mt_yoy_pct       float64
dap_fertiliser_usd_mt_mom_pct    float64
dap_fertiliser_usd_mt_yoy_pct    float64
mop_potash_usd_mt_mom_pct        float64
mop_potash_usd_mt_yoy_pct        float64
dap_to_wheat_ratio               float64
fertiliser_composite_idx         float64
dtype: object

In [23]:
crop.dtypes

year                                  int64
maize_area_mha                      float64
maize_production_mt                 float64
rice_paddy_area_mha                 float64
rice_paddy_production_mt            float64
wheat_area_mha                      float64
wheat_production_mt                 float64
wheat_production_mt_yoy_pct         float64
rice_paddy_production_mt_yoy_pct    float64
maize_production_mt_yoy_pct         float64
total_staple_production_mt          float64
dtype: object

In [24]:
fsi.dtypes

year                               int64
undernourishment_pct             float64
food_production_index            float64
cereal_yield_kg_ha               float64
arable_land_pct                  float64
undernourishment_pct_yoy_chg     float64
food_production_index_yoy_chg    float64
cereal_yield_kg_ha_yoy_chg       float64
dtype: object

In [25]:
panel.dtypes

date                              object
soybean_oil_usd_mt               float64
maize_usd_mt                     float64
wheat_usd_mt                     float64
dap_fertiliser_usd_mt            float64
mop_potash_usd_mt                float64
wheat_usd_mt_mom_pct             float64
wheat_usd_mt_yoy_pct             float64
maize_usd_mt_mom_pct             float64
maize_usd_mt_yoy_pct             float64
soybean_oil_usd_mt_mom_pct       float64
soybean_oil_usd_mt_yoy_pct       float64
dap_fertiliser_usd_mt_mom_pct    float64
dap_fertiliser_usd_mt_yoy_pct    float64
mop_potash_usd_mt_mom_pct        float64
mop_potash_usd_mt_yoy_pct        float64
dap_to_wheat_ratio               float64
fertiliser_composite_idx         float64
undernourishment_pct             float64
food_production_index            float64
cereal_yield_kg_ha               float64
arable_land_pct                  float64
undernourishment_pct_yoy_chg     float64
food_production_index_yoy_chg    float64
cereal_yield_kg_ha_yoy_chg       float64
ffpi_overall                     float64
ffpi_cereals                     float64
ffpi_overall_mom_pct             float64
ffpi_cereals_yoy_pct             float64
ffpi_above_baseline                int64
ffpi_crisis_flag                   int64
dap_to_wheat_elevated              int64
ffpi_volatility_12m              float64
cereals_affordability_idx        float64
supply_stress_flag                 int64
food_shock_score                   int64
month                              int64
year                               int64
dtype: object

In [26]:
commodity.isnull().sum()

date                              0
soybean_oil_usd_mt                0
maize_usd_mt                      0
wheat_usd_mt                      0
dap_fertiliser_usd_mt            84
mop_potash_usd_mt                 0
wheat_usd_mt_mom_pct              1
wheat_usd_mt_yoy_pct             12
maize_usd_mt_mom_pct              1
maize_usd_mt_yoy_pct             12
soybean_oil_usd_mt_mom_pct        1
soybean_oil_usd_mt_yoy_pct       12
dap_fertiliser_usd_mt_mom_pct    85
dap_fertiliser_usd_mt_yoy_pct    96
mop_potash_usd_mt_mom_pct         1
mop_potash_usd_mt_yoy_pct        12
dap_to_wheat_ratio               84
fertiliser_composite_idx          0
dtype: int64

In [27]:
crop.isnull().sum()

year                                0
maize_area_mha                      0
maize_production_mt                 0
rice_paddy_area_mha                 0
rice_paddy_production_mt            0
wheat_area_mha                      0
wheat_production_mt                 0
wheat_production_mt_yoy_pct         1
rice_paddy_production_mt_yoy_pct    1
maize_production_mt_yoy_pct         1
total_staple_production_mt          0
dtype: int64

In [28]:
fsi.isnull().sum()

year                              0
undernourishment_pct             40
food_production_index             3
cereal_yield_kg_ha                3
arable_land_pct                   3
undernourishment_pct_yoy_chg     41
food_production_index_yoy_chg     4
cereal_yield_kg_ha_yoy_chg        4
dtype: int64

In [29]:
panel.isnull().sum()

date                               0
soybean_oil_usd_mt                 0
maize_usd_mt                       0
wheat_usd_mt                       0
dap_fertiliser_usd_mt              0
mop_potash_usd_mt                  0
wheat_usd_mt_mom_pct               0
wheat_usd_mt_yoy_pct               0
maize_usd_mt_mom_pct               0
maize_usd_mt_yoy_pct               0
soybean_oil_usd_mt_mom_pct         0
soybean_oil_usd_mt_yoy_pct         0
dap_fertiliser_usd_mt_mom_pct      0
dap_fertiliser_usd_mt_yoy_pct      0
mop_potash_usd_mt_mom_pct          0
mop_potash_usd_mt_yoy_pct          0
dap_to_wheat_ratio                 0
fertiliser_composite_idx           0
undernourishment_pct             144
food_production_index             37
cereal_yield_kg_ha                 1
arable_land_pct                   13
undernourishment_pct_yoy_chg     156
food_production_index_yoy_chg     37
cereal_yield_kg_ha_yoy_chg         1
ffpi_overall                       0
ffpi_cereals                       0
ffpi_overall_mom_pct               1
ffpi_cereals_yoy_pct              12
ffpi_above_baseline                0
ffpi_crisis_flag                   0
dap_to_wheat_elevated              0
ffpi_volatility_12m               12
cereals_affordability_idx          0
supply_stress_flag                 0
food_shock_score                   0
month                              0
year                               0
dtype: int64

In [30]:
commodity.duplicated().sum()

np.int64(0)

In [31]:
crop.duplicated().sum()

np.int64(0)

In [32]:
fsi.duplicated().sum()

np.int64(0)

In [33]:
panel.duplicated().sum()

np.int64(0)

In [34]:
commodity.describe()

,soybean_oil_usd_mt,maize_usd_mt,wheat_usd_mt,dap_fertiliser_usd_mt,mop_potash_usd_mt,wheat_usd_mt_mom_pct,wheat_usd_mt_yoy_pct,maize_usd_mt_mom_pct,maize_usd_mt_yoy_pct,soybean_oil_usd_mt_mom_pct,soybean_oil_usd_mt_yoy_pct,dap_fertiliser_usd_mt_mom_pct,dap_fertiliser_usd_mt_yoy_pct,mop_potash_usd_mt_mom_pct,mop_potash_usd_mt_yoy_pct,dap_to_wheat_ratio,fertiliser_composite_idx
count,780.000000,780.000000,780.000000,696.000000,780.000000,779.000000,768.000000,779.000000,768.000000,779.000000,768.000000,695.000000,684.000000,779.000000,768.000000,696.000000,780.000000
mean,606.147099,126.478807,163.378153,253.780991,159.185006,0.352856,5.445513,0.347864,5.033879,0.405522,6.685598,0.550119,10.009877,0.530159,8.432786,1.359489,194.417872
std,329.001502,65.851950,84.389482,177.368188,165.688816,6.001040,27.407049,5.588467,25.373859,6.342206,32.727376,7.131971,40.641109,7.164735,38.128695,0.423997,166.962917
min,157.000000,38.000000,52.180000,54.000000,22.000000,-19.681000,-47.470000,-21.717000,-46.380000,-21.523000,-56.166000,-37.601000,-75.529000,-41.466000,-70.233000,0.664000,27.500000
25%,358.892500,86.430000,109.092500,145.187500,56.000000,-2.579000,-12.512750,-2.516000,-10.388250,-3.128500,-13.344000,-1.880500,-11.521250,0.000000,-5.882000,1.065500,97.000000
50%,544.000000,111.000000,151.101768,185.125000,112.500000,0.000000,0.000000,0.000000,0.551500,0.000000,-0.248000,0.000000,1.871000,0.000000,0.000000,1.254500,135.590000
75%,770.350000,158.014294,195.303323,334.538750,206.500000,2.681000,17.265000,3.049500,14.431500,3.277000,19.510250,2.440000,20.876000,0.000000,13.236250,1.560500,267.130000
max,1962.880000,348.166655,522.290000,1075.750000,1202.000000,67.952000,210.048000,34.651000,119.960000,46.872000,178.243000,62.264000,223.333000,70.841000,247.902000,3.833000,1078.000000

In [35]:
crop.describe()

,year,maize_area_mha,maize_production_mt,rice_paddy_area_mha,rice_paddy_production_mt,wheat_area_mha,wheat_production_mt,wheat_production_mt_yoy_pct,rice_paddy_production_mt_yoy_pct,maize_production_mt_yoy_pct,total_staple_production_mt
count,64.000000,64.000000,6.400000e+01,64.000000,64.000000,64.000000,64.000000,63.000000,63.000000,63.000000,6.400000e+01
mean,1992.500000,143774.627203,6.034036e+05,147354.200578,521617.481484,220380.209953,534518.812453,2.236032,2.190730,3.186952,1.659540e+06
std,18.618987,30978.165432,3.112267e+05,13213.316250,177073.632094,7547.198746,164675.083750,6.282446,3.146929,8.163564,6.445897e+05
min,1961.000000,103496.472000,2.048766e+05,115365.128000,215646.627000,204209.450000,222357.231000,-8.953000,-3.875000,-22.687000,6.430311e+05
25%,1976.750000,123130.516000,3.510673e+05,141511.729250,366351.555500,215657.524500,410470.192500,-2.206500,-0.153000,-1.521500,1.122501e+06
50%,1992.500000,134760.722500,5.058008e+05,147412.020500,528973.640500,219540.128500,555535.148000,0.796000,1.923000,2.433000,1.599218e+06
75%,2008.250000,160517.333250,8.235942e+05,157509.075750,681642.699000,225157.216000,655286.561250,5.936000,4.154000,6.900500,2.188758e+06
max,2024.000000,211099.135000,1.238583e+06,172414.425000,820223.278000,239165.634000,807987.812000,18.005000,9.124000,29.782000,2.837894e+06

In [36]:
fsi.describe()

,year,undernourishment_pct,food_production_index,cereal_yield_kg_ha,arable_land_pct,undernourishment_pct_yoy_chg,food_production_index_yoy_chg,cereal_yield_kg_ha_yoy_chg
count,63.000000,23.000000,60.000000,60.000000,60.000000,22.000000,59.000000,59.000000
mean,1992.000000,9.334783,50.337846,2895.109201,10.389908,-0.195455,1.476271,45.196390
std,18.330303,1.949967,36.986079,774.402772,0.348589,0.364466,4.496355,82.664559
min,1961.000000,7.300000,12.899822,1576.946325,9.642818,-0.900000,-5.349000,-107.262000
25%,1976.500000,7.800000,19.357923,2297.148074,10.104274,-0.400000,0.000000,-12.367000
50%,1992.000000,8.600000,25.532460,2841.340868,10.576059,-0.100000,0.588000,40.749000
75%,2007.500000,10.550000,99.287589,3539.273490,10.650773,-0.100000,1.710500,83.927500
max,2023.000000,12.900000,104.629639,4243.531108,10.707616,0.500000,30.070000,287.315000

In [37]:
panel.describe()

,soybean_oil_usd_mt,maize_usd_mt,wheat_usd_mt,dap_fertiliser_usd_mt,mop_potash_usd_mt,wheat_usd_mt_mom_pct,wheat_usd_mt_yoy_pct,maize_usd_mt_mom_pct,maize_usd_mt_yoy_pct,soybean_oil_usd_mt_mom_pct,...,ffpi_cereals_yoy_pct,ffpi_above_baseline,ffpi_crisis_flag,dap_to_wheat_elevated,ffpi_volatility_12m,cereals_affordability_idx,supply_stress_flag,food_shock_score,month,year
count,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,...,408.000000,420.000000,420.000000,420.000000,408.00000,420.000000,420.000000,420.000000,420.000000,420.00000
mean,776.715327,160.854236,209.208213,324.072905,247.781024,0.297755,4.658467,0.320305,4.665286,0.360655,...,4.691917,0.311905,0.195238,0.002381,4.15200,121.991619,0.128571,0.326190,6.500000,2007.00000
std,330.284046,67.463825,82.560361,190.777095,182.592420,6.340109,27.640518,5.879735,27.098531,5.492530,...,25.404208,0.463824,0.396857,0.048795,1.49738,42.126239,0.335124,0.622398,3.456169,10.11155
min,286.890000,75.270000,102.160000,112.750000,93.200000,-19.681000,-47.470000,-21.717000,-46.380000,-21.523000,...,-40.376000,0.000000,0.000000,0.000000,1.82100,45.750000,0.000000,0.000000,1.000000,1990.00000
25%,535.957500,105.813025,147.646450,171.575000,112.500000,-3.565750,-15.568750,-2.908000,-11.766000,-2.916750,...,-13.708500,0.000000,0.000000,0.000000,3.10775,86.052500,0.000000,0.000000,3.750000,1998.00000
50%,723.870000,151.881744,189.413619,264.075000,192.500000,-0.009500,0.457000,0.132500,-0.460000,0.000000,...,-0.293000,0.000000,0.000000,0.000000,3.74800,114.340000,0.000000,0.000000,6.500000,2007.00000
75%,962.595000,190.344291,266.880441,422.160000,307.156250,3.785000,21.145250,3.491250,14.509500,3.092250,...,17.884250,1.000000,0.000000,0.000000,4.78850,157.517500,0.000000,0.000000,9.250000,2016.00000
max,1962.880000,348.166655,522.290000,1075.750000,1202.000000,25.753000,120.854000,24.595000,112.160000,46.872000,...,105.028000,1.000000,1.000000,1.000000,9.75100,215.050000,1.000000,2.000000,12.000000,2024.00000

In [38]:
commodity['date'] = pd.to_datetime(commodity['date'])

In [39]:
commodity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           780 non-null    datetime64[ns]
 1   soybean_oil_usd_mt             780 non-null    float64
 2   maize_usd_mt                   780 non-null    float64
 3   wheat_usd_mt                   780 non-null    float64
 4   dap_fertiliser_usd_mt          696 non-null    float64
 5   mop_potash_usd_mt              780 non-null    float64
 6   wheat_usd_mt_mom_pct           779 non-null    float64
 7   wheat_usd_mt_yoy_pct           768 non-null    float64
 8   maize_usd_mt_mom_pct           779 non-null    float64
 9   maize_usd_mt_yoy_pct           768 non-null    float64
 10  soybean_oil_usd_mt_mom_pct     779 non-null    float64
 11  soybean_oil_usd_mt_yoy_pct     768 non-null    float64
 12  dap_fertiliser_usd_mt_mom_pct  695 non-null    float64
 13  dap_fertiliser_usd_mt_yoy_pct  684 non-null    float64
 14  mop_potash_usd_mt_mom_pct      779 non-null    float64
 15  mop_potash_usd_mt_yoy_pct      768 non-null    float64
 16  dap_to_wheat_ratio             696 non-null    float64
 17  fertiliser_composite_idx       780 non-null    float64
dtypes: datetime64[ns](1), float64(17)
memory usage: 109.8 KB

In [40]:
panel['date'] = pd.to_datetime(panel['date'])

In [41]:
panel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 38 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           420 non-null    datetime64[ns]
 1   soybean_oil_usd_mt             420 non-null    float64
 2   maize_usd_mt                   420 non-null    float64
 3   wheat_usd_mt                   420 non-null    float64
 4   dap_fertiliser_usd_mt          420 non-null    float64
 5   mop_potash_usd_mt              420 non-null    float64
 6   wheat_usd_mt_mom_pct           420 non-null    float64
 7   wheat_usd_mt_yoy_pct           420 non-null    float64
 8   maize_usd_mt_mom_pct           420 non-null    float64
 9   maize_usd_mt_yoy_pct           420 non-null    float64
 10  soybean_oil_usd_mt_mom_pct     420 non-null    float64
 11  soybean_oil_usd_mt_yoy_pct     420 non-null    float64
 12  dap_fertiliser_usd_mt_mom_pct  420 non-null    float64
 13  dap_fertiliser_usd_mt_yoy_pct  420 non-null    float64
 14  mop_potash_usd_mt_mom_pct      420 non-null    float64
 15  mop_potash_usd_mt_yoy_pct      420 non-null    float64
 16  dap_to_wheat_ratio             420 non-null    float64
 17  fertiliser_composite_idx       420 non-null    float64
 18  undernourishment_pct           276 non-null    float64
 19  food_production_index          383 non-null    float64
 20  cereal_yield_kg_ha             419 non-null    float64
 21  arable_land_pct                407 non-null    float64
 22  undernourishment_pct_yoy_chg   264 non-null    float64
 23  food_production_index_yoy_chg  383 non-null    float64
 24  cereal_yield_kg_ha_yoy_chg     419 non-null    float64
 25  ffpi_overall                   420 non-null    float64
 26  ffpi_cereals                   420 non-null    float64
 27  ffpi_overall_mom_pct           419 non-null    float64
 28  ffpi_cereals_yoy_pct           408 non-null    float64
 29  ffpi_above_baseline            420 non-null    int64
 30  ffpi_crisis_flag               420 non-null    int64
 31  dap_to_wheat_elevated          420 non-null    int64
 32  ffpi_volatility_12m            408 non-null    float64
 33  cereals_affordability_idx      420 non-null    float64
 34  supply_stress_flag             420 non-null    int64
 35  food_shock_score               420 non-null    int64
 36  month                          420 non-null    int64
 37  year                           420 non-null    int64
dtypes: datetime64[ns](1), float64(30), int64(7)
memory usage: 124.8 KB

In [42]:
num_cols = commodity.select_dtypes(include=np.number).columns

commodity[num_cols] = commodity[num_cols].fillna(
    commodity[num_cols].median()
)

In [43]:
num_cols = crop.select_dtypes(include=np.number).columns

crop[num_cols] = crop[num_cols].fillna(
    crop[num_cols].median()
)

In [44]:
num_cols = fsi.select_dtypes(include=np.number).columns

fsi[num_cols] = fsi[num_cols].fillna(
    fsi[num_cols].median()
)

In [45]:
num_cols = panel.select_dtypes(include=np.number).columns

panel[num_cols] = panel[num_cols].fillna(
    panel[num_cols].median()
)

In [46]:
commodity.isnull().sum()

date                             0
soybean_oil_usd_mt               0
maize_usd_mt                     0
wheat_usd_mt                     0
dap_fertiliser_usd_mt            0
mop_potash_usd_mt                0
wheat_usd_mt_mom_pct             0
wheat_usd_mt_yoy_pct             0
maize_usd_mt_mom_pct             0
maize_usd_mt_yoy_pct             0
soybean_oil_usd_mt_mom_pct       0
soybean_oil_usd_mt_yoy_pct       0
dap_fertiliser_usd_mt_mom_pct    0
dap_fertiliser_usd_mt_yoy_pct    0
mop_potash_usd_mt_mom_pct        0
mop_potash_usd_mt_yoy_pct        0
dap_to_wheat_ratio               0
fertiliser_composite_idx         0
dtype: int64

In [47]:
crop.isnull().sum()

year                                0
maize_area_mha                      0
maize_production_mt                 0
rice_paddy_area_mha                 0
rice_paddy_production_mt            0
wheat_area_mha                      0
wheat_production_mt                 0
wheat_production_mt_yoy_pct         0
rice_paddy_production_mt_yoy_pct    0
maize_production_mt_yoy_pct         0
total_staple_production_mt          0
dtype: int64

In [48]:
fsi.isnull().sum()

year                             0
undernourishment_pct             0
food_production_index            0
cereal_yield_kg_ha               0
arable_land_pct                  0
undernourishment_pct_yoy_chg     0
food_production_index_yoy_chg    0
cereal_yield_kg_ha_yoy_chg       0
dtype: int64

In [49]:
panel.isnull().sum()

date                             0
soybean_oil_usd_mt               0
maize_usd_mt                     0
wheat_usd_mt                     0
dap_fertiliser_usd_mt            0
mop_potash_usd_mt                0
wheat_usd_mt_mom_pct             0
wheat_usd_mt_yoy_pct             0
maize_usd_mt_mom_pct             0
maize_usd_mt_yoy_pct             0
soybean_oil_usd_mt_mom_pct       0
soybean_oil_usd_mt_yoy_pct       0
dap_fertiliser_usd_mt_mom_pct    0
dap_fertiliser_usd_mt_yoy_pct    0
mop_potash_usd_mt_mom_pct        0
mop_potash_usd_mt_yoy_pct        0
dap_to_wheat_ratio               0
fertiliser_composite_idx         0
undernourishment_pct             0
food_production_index            0
cereal_yield_kg_ha               0
arable_land_pct                  0
undernourishment_pct_yoy_chg     0
food_production_index_yoy_chg    0
cereal_yield_kg_ha_yoy_chg       0
ffpi_overall                     0
ffpi_cereals                     0
ffpi_overall_mom_pct             0
ffpi_cereals_yoy_pct             0
ffpi_above_baseline              0
ffpi_crisis_flag                 0
dap_to_wheat_elevated            0
ffpi_volatility_12m              0
cereals_affordability_idx        0
supply_stress_flag               0
food_shock_score                 0
month                            0
year                             0
dtype: int64

In [50]:
commodity.to_csv(
    "commodity_prices_cleaned.csv",
    index=False
)

In [51]:
crop.to_csv(
    "crop_yields_cleaned.csv",
    index=False
)

In [52]:
fsi.to_csv(
    "food_security_indicators_cleaned.csv",
    index=False
)

In [53]:
panel.to_csv(
    "food_security_panel_cleaned.csv",
    index=False
)

In [54]:
commodity.columns

Index(['date', 'soybean_oil_usd_mt', 'maize_usd_mt', 'wheat_usd_mt',
       'dap_fertiliser_usd_mt', 'mop_potash_usd_mt', 'wheat_usd_mt_mom_pct',
       'wheat_usd_mt_yoy_pct', 'maize_usd_mt_mom_pct', 'maize_usd_mt_yoy_pct',
       'soybean_oil_usd_mt_mom_pct', 'soybean_oil_usd_mt_yoy_pct',
       'dap_fertiliser_usd_mt_mom_pct', 'dap_fertiliser_usd_mt_yoy_pct',
       'mop_potash_usd_mt_mom_pct', 'mop_potash_usd_mt_yoy_pct',
       'dap_to_wheat_ratio', 'fertiliser_composite_idx'],
      dtype='object')

In [55]:
crop.columns

Index(['year', 'maize_area_mha', 'maize_production_mt', 'rice_paddy_area_mha',
       'rice_paddy_production_mt', 'wheat_area_mha', 'wheat_production_mt',
       'wheat_production_mt_yoy_pct', 'rice_paddy_production_mt_yoy_pct',
       'maize_production_mt_yoy_pct', 'total_staple_production_mt'],
      dtype='object')

In [56]:
fsi.columns

Index(['year', 'undernourishment_pct', 'food_production_index',
       'cereal_yield_kg_ha', 'arable_land_pct', 'undernourishment_pct_yoy_chg',
       'food_production_index_yoy_chg', 'cereal_yield_kg_ha_yoy_chg'],
      dtype='object')

In [57]:
panel.columns

Index(['date', 'soybean_oil_usd_mt', 'maize_usd_mt', 'wheat_usd_mt',
       'dap_fertiliser_usd_mt', 'mop_potash_usd_mt', 'wheat_usd_mt_mom_pct',
       'wheat_usd_mt_yoy_pct', 'maize_usd_mt_mom_pct', 'maize_usd_mt_yoy_pct',
       'soybean_oil_usd_mt_mom_pct', 'soybean_oil_usd_mt_yoy_pct',
       'dap_fertiliser_usd_mt_mom_pct', 'dap_fertiliser_usd_mt_yoy_pct',
       'mop_potash_usd_mt_mom_pct', 'mop_potash_usd_mt_yoy_pct',
       'dap_to_wheat_ratio', 'fertiliser_composite_idx',
       'undernourishment_pct', 'food_production_index', 'cereal_yield_kg_ha',
       'arable_land_pct', 'undernourishment_pct_yoy_chg',
       'food_production_index_yoy_chg', 'cereal_yield_kg_ha_yoy_chg',
       'ffpi_overall', 'ffpi_cereals', 'ffpi_overall_mom_pct',
       'ffpi_cereals_yoy_pct', 'ffpi_above_baseline', 'ffpi_crisis_flag',
       'dap_to_wheat_elevated', 'ffpi_volatility_12m',
       'cereals_affordability_idx', 'supply_stress_flag', 'food_shock_score',
       'month', 'year'],
      dtype='object')

In [58]:
avg_food_price_index = panel['ffpi_overall'].mean()

print("Average Food Price Index:", avg_food_price_index)

Average Food Price Index: 94.08240476190477

In [59]:
avg_wheat_price = panel['wheat_usd_mt'].mean()

print("Average Wheat Price:", avg_wheat_price)

Average Wheat Price: 209.2082134357173

In [60]:
avg_maize_price = panel['maize_usd_mt'].mean()

print("Average Maize Price:", avg_maize_price)

Average Maize Price: 160.85423649424325

In [61]:
avg_fertilizer_index = panel['fertiliser_composite_idx'].mean()

print("Average Fertilizer Index:", avg_fertilizer_index)

Average Fertilizer Index: 285.92697619047624

In [62]:
avg_crop_yield = crop['total_staple_production_mt'].mean()

print("Average Crop Yield:", avg_crop_yield)

Average Crop Yield: 1659539.922640625

In [63]:
avg_mom_growth = panel['ffpi_overall_mom_pct'].mean()

print("Average MOM Growth %:", avg_mom_growth)

Average MOM Growth %: 0.25845714285714283

In [64]:
panel = panel.sort_values('date')

panel['ffpi_overall_yoy_pct'] = (
    panel['ffpi_overall']
    .pct_change(periods=12)
) * 100

In [65]:
panel[['date','ffpi_overall','ffpi_overall_yoy_pct']].head(20)

         date  ffpi_overall  ffpi_overall_yoy_pct
0  1990-01-31         62.67                   NaN
1  1990-02-28         62.14                   NaN
2  1990-03-31         62.73                   NaN
3  1990-04-30         64.85                   NaN
4  1990-05-31         64.07                   NaN
5  1990-06-30         61.40                   NaN
6  1990-07-31         58.72                   NaN
7  1990-08-31         57.48                   NaN
8  1990-09-30         55.49                   NaN
9  1990-10-31         55.60                   NaN
10 1990-11-30         54.81                   NaN
11 1990-12-31         56.02                   NaN
12 1991-01-31         55.60            -11.281315
13 1991-02-28         55.67            -10.411973
14 1991-03-31         57.49             -8.353260
15 1991-04-30         58.15            -10.331534
16 1991-05-31         56.78            -11.378180
17 1991-06-30         56.05             -8.713355
18 1991-07-31         55.58             -5.347411
19 1991-08-31         58.72              2.157272

In [66]:
avg_yoy_growth = panel['ffpi_overall_yoy_pct'].mean()

print(avg_yoy_growth)

4.574046827112833

In [67]:
crisis_count = panel['ffpi_crisis_flag'].sum()

print("Crisis Count:", crisis_count)

Crisis Count: 82

In [68]:
supply_stress_count = panel['supply_stress_flag'].sum()

print("Supply Stress Count:", supply_stress_count)

Supply Stress Count: 54

In [69]:
kpi_summary = pd.DataFrame({
    'Metric':[
        'Average Food Price Index',
        'Average Wheat Price',
        'Average Maize Price',
        'Average Fertilizer Index',
        'Average Crop Yield',
        'Average MOM Growth %',
        'Average YOY Growth %',
        'Crisis Count',
        'Supply Stress Count'
    ],
    'Value':[
        avg_food_price_index,
        avg_wheat_price,
        avg_maize_price,
        avg_fertilizer_index,
        avg_crop_yield,
        avg_mom_growth,
        avg_yoy_growth,
        crisis_count,
        supply_stress_count
    ]
})

kpi_summary

                     Metric         Value
0  Average Food Price Index  9.408240e+01
1       Average Wheat Price  2.092082e+02
2       Average Maize Price  1.608542e+02
3  Average Fertilizer Index  2.859270e+02
4        Average Crop Yield  1.659540e+06
5      Average MOM Growth %  2.584571e-01
6      Average YOY Growth %  4.574047e+00
7              Crisis Count  8.200000e+01
8       Supply Stress Count  5.400000e+01

In [70]:
panel.to_csv(
    'food_security_panel_cleaned1.csv',
    index=False
)

In [71]:
kpi_summary.to_csv(
    'kpi_summary.csv',
    index=False
)

In [72]:
wheat = panel['wheat_usd_mt']

print("Mean:", np.mean(wheat))
print("Median:", np.median(wheat))
print("Std:", np.std(wheat))
print("Variance:", np.var(wheat))
print("Max:", np.max(wheat))
print("Min:", np.min(wheat))

Mean: 209.2082134357173
Median: 189.41361885
Std: 82.46201593673037
Variance: 6799.984072349573
Max: 522.29
Min: 102.16

In [73]:
maize = panel['maize_usd_mt']

print("Mean:", np.mean(maize))
print("Median:", np.median(maize))
print("Std:", np.std(maize))
print("Variance:", np.var(maize))
print("Max:", np.max(maize))
print("Min:", np.min(maize))

Mean: 160.85423649424325
Median: 151.881744
Std: 67.383462793952
Variance: 4540.531058103914
Max: 348.1666552
Min: 75.27

In [74]:
soybeanoil = panel['soybean_oil_usd_mt']

print("Mean:", np.mean(soybeanoil))
print("Median:", np.median(soybeanoil))
print("Std:", np.std(soybeanoil))
print("Variance:", np.var(soybeanoil))
print("Max:", np.max(soybeanoil))
print("Min:", np.min(soybeanoil))

Mean: 776.7153272471036
Median: 723.87
Std: 329.8906165986588
Variance: 108827.8189198433
Max: 1962.88
Min: 286.89

In [75]:
foodshock = panel['food_shock_score']

print("Mean:", np.mean(foodshock))
print("Median:", np.median(foodshock))
print("Std:", np.std(foodshock))
print("Variance:", np.var(foodshock))
print("Max:", np.max(foodshock))
print("Min:", np.min(foodshock))

Mean: 0.3261904761904762
Median: 0.0
Std: 0.6216565901683769
Variance: 0.38645691609977334
Max: 2
Min: 0

In [76]:
fertilisercomposite = panel['fertiliser_composite_idx']

print("Mean:", np.mean(fertilisercomposite))
print("Median:", np.median(fertilisercomposite))
print("Std:", np.std(fertilisercomposite))
print("Variance:", np.var(fertilisercomposite))
print("Max:", np.max(fertilisercomposite))
print("Min:", np.min(fertilisercomposite))

Mean: 285.92697619047624
Median: 252.04000000000002
Std: 177.04827950415216
Variance: 31346.093275380383
Max: 1078.0
Min: 112.62

In [77]:
commodity.shape

(780, 18)

In [78]:
crop.shape

(64, 11)

In [79]:
fsi.shape

(63, 8)

In [80]:
panel.shape

(420, 39)